### ISSUE TITLE
documentation for variables passed to templates?

### ISSUE THREAD

**Issue by tmcw** [segmentio/metalsmith#107]
It looks like the set of things passed to templates, like `contents`, is just a bit different from Jekyll. It would be useful to have the default set of variables documented.

**Comment by sperand-io** [comment]
hey there! good question. 

in fact, all metalsmith teases out for a given file is that file's explicitly set metadata (in yaml) and contents.

so this:

```
---
title: A Catchy Title
date: 2014-12-01
---

An informative article.
```

becomes: 

```
{
  'path/to/my-file.md': {
    title: 'A Catchy Title',
    date: new Date('2014-12-01'),
    contents: new Buffer('An informative article.')
  }
}
```

any further variables/properties appended to the post that get sent to the template are done in the "pipeline"... either passed by you into the global metadata via the `.metadata()`method (like we do here: https://github.com/segmentio/metalsmith.io/blob/fb9895ba577e6ade83648e9930ebb7fbd4a854de/build.js#L42-L45)

...or put there by plugins, ie: 

permalinks -> data.path: https://github.com/segmentio/metalsmith-permalinks/blob/master/lib/index.js#L54

excerpts -> data.excerpt: https://github.com/segmentio/metalsmith-excerpts/blob/master/lib/index.js#L30

wordcount -> https://github.com/majodev/metalsmith-word-count/blob/master/index.js#L40-L41

lmk if that makes sense!

**Comment by tmcw** [comment]
Okay, so:

> in fact, all metalsmith teases out for a given file is that file's explicitly set metadata (in yaml) and contents.

This could be explicitly stated. Also the `contents` variable should be explicitly stated: I guessed `content` (like jekyll) and `body` (like wp) before hunting down examples and finding the magic word.

**Comment by ianstormtaylor** [comment]
Good idea, would gladly accept PRs in this direction!
