### ISSUE TITLE
Generating an absolute path from metalsmith.json

### ISSUE THREAD

**Issue by christophercliff** [segmentio/metalsmith#119]
Suppose a plugin requires an absolute path, but you don't want to hard code it in `metalsmith.json` (https://github.com/christophercliff/metalsmith-webpack/issues/6).

Are there any implementations out there? Any consensus?

**Comment by ianstormtaylor** [comment]
What kind of thing are you thinking as far as implementation? what's the reason to not hardcode?

For the `source` and `destination` properties in `metalsmith.json` you should be able to pass absolute paths there and have it work normally.

**Comment by ianstormtaylor** [comment]
Cc @christophercliff you ever figure this one out? Still relevant?

**Comment by christophercliff** [comment]
Nah.
