### ISSUE TITLE
Metalsmith Javascript API does not convert markdown but json config does

### ISSUE THREAD

**Issue by kartoch** [segmentio/metalsmith#120]
I'm trying to convert my simple site. The following 'metalsmith.json' works as expected:

    {
      "metadata": {},
      "plugins": {
        "metalsmith-markdown": {},
        "metalsmith-permalinks": {
          "pattern": ":title"
        },
        "metalsmith-templates": {
          "engine": "handlebars"
        }
      }
    }

But same configuration using javascript fails: all *.md files are simply copied to the build directory (nor template neither markdown conversion). The 'build.js' is the following:

    var Metalsmith = require('metalsmith');
    var markdown   = require('metalsmith-markdown');
    var templates  = require('metalsmith-templates');
    var permalinks = require('metalsmith-permalinks');
    
    Metalsmith(__dirname)
        .use(markdown())
        .use(templates({engine: 'handlebars'}))
        .use(permalinks({pattern: ":title"}))
        .destination('build')
        .build(function(err) {
        if (err) throw err;
      });

My 'package.json':

    {
      "name": "hello-world",
      "private": true,
      "dependencies": {
        "metalsmith-templates": "^0.6.0",
        "metalsmith-markdown": "^0.2.1",
        "metalsmith-permalinks": "^0.4.0",
        "metalsmith": "^1.3.0",
        "handlebars": "^2.0.0"
      }
    }

**Comment by ianstormtaylor** [comment]
Looks like the order is different between the two setups

**Comment by kartoch** [comment]
Inversing use of permalins and template solves the problem:

    var Metalsmith = require('metalsmith');
    var markdown   = require('metalsmith-markdown');
    var templates  = require('metalsmith-templates');
    var permalinks = require('metalsmith-permalinks');
    
    Metalsmith(__dirname)
        .use(markdown())
        .use(permalinks({pattern: ":title"}))
        .use(templates({engine: 'handlebars'}))
        .destination('build')
        .build(function(err) {
          if (err) throw err;
        });

But I've only small problem: the `index.md` is copied as is in the `build` directory. How can I have only the generated HTML in build` ?

**Comment by lyzadanger** [comment]
This is my first use of metalsmith (in the past I've rolled my own static-site generators with grunt/gulp). I was running into a similar wall. My build script looked like:

```javascript
var Handlebars = require('handlebars');
var metalsmith = require('metalsmith');
var markdown   = require('metalsmith-markdown');
var permalinks = require('metalsmith-permalinks');
var templates  = require('metalsmith-templates');

var smithy = metalsmith(__dirname)
  .use(markdown)
  .use(permalinks({
    pattern: ':title'
  }))
  .use(templates({
    engine: 'handlebars',
    directory: 'templates'
  }))
  .destination('./build')
  .build(function (err, files) {
    if (err) { throw err; }
  });
```

Correspondingly, I have a basic `.hbt` template in `templates/post.hbt` that I am referencing from the front matter of my single example post in `src/posts/whatever.md`

```yaml
---
title: "I have a title"
date: 2015-02-13
template: post.hbt
---

(contents in markdown...)
```

When I built the site, I would see the following:

* `build/posts/whatever.md` is created. No renaming is occurring. This is unexpected.
* The contents of `build/posts/whatever.md` is HTML from `templates/post.hbt`. Other metadata (e.g. `title`) are rendered as expected. This is as expected.
* The `contents` data is rendered as raw markdown (not HTML). This is unexpected.

I am using:

```json
  "dependencies": {
    "handlebars": "^3.0.0",
    "metalsmith": "^1.3.0",
    "metalsmith-markdown": "^0.2.1",
    "metalsmith-permalinks": "^0.4.0",
    "metalsmith-templates": "^0.6.0"
  }
```

### My fix

In my build script, changing

`  .use(markdown)`

to

```javascript
.use(markdown({
  gfm: true
})
```

fixed both symptoms in my case:

* Now I get `build/whatevers/index.html`
* Contents of `contents` are HTML-ized correctly

This seems odd to me, still, and was a frustration for a while. Possibly a documentation gotcha?

**Comment by ianstormtaylor** [comment]
Closing, but feel free to re-open if still an issue!
