### ISSUE TITLE
CLI obscures plugin exceptions

### ISSUE THREAD

**Issue by christophercliff** [segmentio/metalsmith#125]
Validating plugin input, e.g. https://github.com/christophercliff/metalsmith-less/blob/master/lib/index.js#L22. Meaningful exceptions get output as `failed to require plugin`.

Causes issues like this https://github.com/christophercliff/metalsmith-less/issues/15.

Relevant lines https://github.com/segmentio/metalsmith/blob/e2f045f4da0d7cb02d3f56b317a603ef743540f2/bin/metalsmith#L79-L93

**Comment by ianstormtaylor** [comment]
solved in `1.4.5`, with message & stacktrace from the plugin!
