### ISSUE TITLE
How do you run a bash script to cleanup the build folder post compilation?

### ISSUE THREAD

**Issue by drevasvoyage** [segmentio/metalsmith#126]
```
var Metalsmith = require('metalsmith'),
    copy       = require('metalsmith-copy'),
    define     = require('metalsmith-define'),
    markdown   = require('metalsmith-markdown'),
    permalinks = require('metalsmith-permalinks'),
    static     = require('metalsmith-static'),
    templates  = require('metalsmith-templates'),


Metalsmith(__dirname)
    .source('./pages')
    .use(static(require('./config/assets')))
    .use(static(require('./config/rootFiles')))
    .use(define(require('./config/define')))
    .use(markdown())
    .use(permalinks())
    .use(templates(require('./config/templates')))
    .destination('./build')
    .build(function (err) {
        if (err) {
          throw err
        }
    })
```

I have a pretty simple build.js but at the end of the build I want to remove the scss folder that the static plugin copies over.

I have a simple bash script in ./config/cleanup.sh

```
#!/bin/bash
rm -rf /Users/me/mysite/build/assets/scss
```

but don't know how to run it as part of the build.

Any pointers would be gratefully received.

**Comment by azurelogic** [comment]
Have you looked at the [Ignore](https://github.com/segmentio/metalsmith-ignore) plugin? Seems like that at the end of your plugin chain could solve your problem.

**Comment by drevasvoyage** [comment]
Thanks for the response azurelogic -- I have looked at ignore, but it only ignores folders in the source directory; I want a folder in the assets directory (that is outside the source directory, but part of the cwd -- don't ask) to be ignored, or to be cleaned up post build.

**Comment by azurelogic** [comment]
Sorry, I didn't read that carefully enough. Another option is to run a second build. This allows for other processing steps, including the ignore plugin. This works as long as your child build's destination directory is a descendant of the destination directory of the parent build, and the parent build can't have any files going into that path (they'll just get blown away when the child build kicks off).

```
var Metalsmith = require('metalsmith'),
    copy       = require('metalsmith-copy'),
    define     = require('metalsmith-define'),
    markdown   = require('metalsmith-markdown'),
    permalinks = require('metalsmith-permalinks'),
    static     = require('metalsmith-static'),
    templates  = require('metalsmith-templates'),


Metalsmith(__dirname)
    .source('./pages')
    .use(static(require('./config/assets')))
    .use(static(require('./config/rootFiles')))
    .use(define(require('./config/define')))
    .use(markdown())
    .use(permalinks())
    .use(templates(require('./config/templates')))
    .destination('./build')
    .build(function (err) {
        if (err) {
          throw err;
        }
        Metalsmith(__dirname)
            .source('./config')
            .destination('./build/config')
            .ignore(...)
            .build(function (err) {
                        if (err) {
                         throw err;
                       });
    });
```

**Comment by ianstormtaylor** [comment]
Should be able to use [`child_process.exec`](https://nodejs.org/api/child_process.html) in the `build` callback, if you just want to run the cleanup script. Closing since this is outside the scope of Metalsmith
