### ISSUE TITLE
gnode is preventing me for using babel-node for my local files

### ISSUE THREAD

**Issue by MoOx** [segmentio/metalsmith#132]
I can't do an import of a js file that contains import because of gnode.
Note sure if this should belong here :/

```
> babel-node --stage 0 scripts/build

/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/scripts/metalsmith/react-templates.js:1
(function (exports, require, module, __filename, __dirname) { import fs from "
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.gnodeJsExtensionCompiler [as .js] (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/metalsmith/node_modules/gnode/index.js:61:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/scripts/build.js:6:43)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/MoOx/Sync/Development/putaindecode/putaindecode.fr/node_modules/babel-core/lib/babel/api/register/node.js:122:5)
```

You can see in the middle of the stack that gnode is hijaking the import and do not handle every es6 stuff like babel does.
Poor workaround is to rename to .es(6) since babel-node handle those extensions :(

**Comment by MoOx** [comment]
@ianstormtaylor any idea how to fix that?
Can't we just scope gnode for your import?
Maybe we should transpile before publising this module instead of doing that on runtime?
It seems so wrong to hijack all required files including the one your don't write. It's so annoying to have to rename all files to anything that .js...

**Comment by ianstormtaylor** [comment]
cc @dominicbarnes got any ideas here for what we should be doing to make this couth?

**Comment by dominicbarnes** [comment]
In duo, we have 2 bins, `duo` and `_duo`.

`duo` is a simple "interceptor", which takes spawns `_duo` with the `--harmony-generators` flag only when generators are unsupported natively. (mocha does this same thing)

This drops `gnode` as a hard dependency, and thus support for node 0.10. But, the trade-off is it allows support for node 0.11+ (including iojs) as well as people who wish to use transpilers like babel.

**Comment by dominicbarnes** [comment]
I believe simply dropping [this line](https://github.com/segmentio/metalsmith/blob/master/index.js#L6) will fix this issue. (while leaving the CLI to require gnode)

However, I think my previous idea is the one that gives the widest support in the long-term.

**Comment by MoOx** [comment]
Can't we try support in JS before requiring gnode ?
ike testing node version or something ?

**Comment by dominicbarnes** [comment]
@MoOx that's what a `metalsmith` "proxy" for `_metalsmith` would do.

Besides, version-sniffing is almost never what you want to do.

**Comment by MoOx** [comment]
Yeah I know, but don't know how to handle that.
Is there still people using 0.10 ? :trollface:

**Comment by dominicbarnes** [comment]
That's the beauty of this solution though, it enables _all_ versions of node to be work. Core would support node 0.11+ (and iojs) natively. The `_metalsmith` bin can be called upon by node 0.10 users. using `gnode` (or even `babel-node` in your case)

```sh
# normal use
$ metalsmith

# node 0.11+ and iojs users (metalsmith installed locally)
$ ./node_modules/.bin/metalsmith

# node 0.10 users
$ gnode ./node_modules/.bin/_metalsmith

# node 0.10 users (gnode installed locally)
$ ./node_modules/.bin/gnode ./node_modules/.bin/_metalsmith

# babel users
$ babel-node ./node_modules/.bin/_metalsmith

# babel users (babel installed locally)
$ ./node_modules/.bin/babel-node ./node_modules/.bin/_metalsmith
```

**Comment by MoOx** [comment]
Do you want a PR for that ?

**Comment by dominicbarnes** [comment]
PRs are always welcome of course, but @ianstormtaylor will likely make the final call on this one.

**Comment by MoOx** [comment]
@dominicbarnes babel-node should not need to use the same bin as node 0.10 ? Why did you write that ?

@ianstormtaylor open for a PR for this with the solution @dominicbarnes explained (`_metalsmith` bin for node 0.10 user, `metalsmith` otherwise)?

**Comment by dominicbarnes** [comment]
@MoOx yeah, my mistake. Only `metalsmith` should be needed, the `_metalsmith` proxy is just an internal detail.

**Comment by ianstormtaylor** [comment]
@MoOx totally open to that!

**Comment by ianstormtaylor** [comment]
Ah just saw https://github.com/segmentio/metalsmith/pull/143 next in my email :)
