### ISSUE TITLE
why metalsmith 1.6 can not work

### ISSUE THREAD

**Issue by VincentWang1009** [segmentio/metalsmith#133]
hi, I found a [toturial](https://github.com/RobinThrift/metalsmith-tutorial/tree/END-OF-PART-1) to start to use metalsmith, it did work use his code. but when i use the latest metalsmith(1.6),
the code below
```
var Metalsmith = require('metalsmith'),
    markdown   = require('metalsmith-markdown'),
    templates  = require('metalsmith-templates');


Metalsmith(__dirname)
    .use(markdown())
    .use(templates('handlebars'))
    .destination('./build')
    .build()

```
did not work ,there's no build folder generated and no err msg.
why is it?

**Comment by 1cgonza** [comment]
Same problem as this: https://github.com/segmentio/metalsmith/issues/92

The solution that works for me is to pass a callback to the build() as suggested here: https://github.com/segmentio/metalsmith/issues/92#issuecomment-61054889

**Comment by tmschl** [comment]
1.6 and some earlier versions need to have a callback in `.build()` all you need to do is add a simple error handler
```
  .build(function(err) {
    if (err) throw err;
  });
```
Also @ianstormtaylor updated the readme recently to address this issue (though it isn't explicitly called out an error handler was added to `.build()` in the readme)

**Comment by deltamualpha** [comment]
This appears to be the case in my fresh install of 1.7.0 as well; nothing happened until I added that error callback to the .build() step.

**Comment by StevenHallLtd** [comment]
+1 with a fresh install - thanks for the tip!

**Comment by shanefulmer** [comment]
I'm still getting this in 1.7 as well - had me stumped for quite a while!

**Comment by ianstormtaylor** [comment]
Closing to consolidate, but this is definitely not great.

**Comment by kongdigital** [comment]
Why is this closed? It's still happening on 2.1.

**Comment by Ajedi32** [comment]
@kongdigital Looks like this was supposedly resolved by an update to the documentation: #104.

Which tutorials are you referring to?

**Comment by woodyrew** [comment]
@Ajedi32 It could be [this tutorial series](http://www.robinthrift.com/posts/getting-to-know-metalsmith/).

Maybe we could have a default handler function:

**Comment by Ajedi32** [comment]
@woodyrew Yeah, unfortunately it's not a trivial change, since the callback bit actually seems to be handled by the `unyield` library. I created a seperate issue for discussing a change like that: #211

**Comment by kongdigital** [comment]
Thinking about this I think on the metalsmith website if you put the example as something like:

```
Metalsmith(__dirname)
  .use(drafts())
  .use(markdown())
  .use(permalinks('posts/:title'))
  .use(layouts('handlebars'))
  .build(function(err) {
    if (err) throw err; // WILL NOT WORK WITHOUT CALLBACK
  });
```

It would make it more obvious that the callback is absolutely necessary.
