### ISSUE TITLE
Having build and output in one place using gh-pages

### ISSUE THREAD

**Issue by mcdonnelldean** [segmentio/metalsmith#140]
Hi all,

First off, amazing tool! Expect docs, plugins and other contributions from myself in the future! I am looking at converting one of our Jekyll based sites to a metalsmith site. So far everything is going swimmingly.

One thing I can't seem to figure out is the correct way to have both the source of the site and it's output exist in the same directory structure in such a way that gh-pages only serves up the output files, not the source ones.

Is it a simple case of having the build in a directory one down from the root and setting the destination to be the root itself, hiding the build by using a `_`?

I just wanted to check if there is a common way used by the community to deploy a metalsmith app to gp-pages. 

__Note:__ that I using the js app structure as opposed to the cli structure in my app if that makes and difference

Thanks a bunch!

**Comment by MoOx** [comment]
Maybe you can use something like this to deploy your build folder https://github.com/X1011/git-directory-deploy (that's what I do for this website https://github.com/putaindecode/putaindecode.fr)

**Comment by McDonnellDean** [comment]
@MoOx Ideally I'd like to keep everything in the one branch, if possible.

**Comment by MoOx** [comment]
Maybe you can check the ignore option recently added.

**Comment by mcdonnelldean** [comment]
@MoOx That doesn't really do anything for me. I've done it the way I said above, I don't really see another way.

**Comment by ianstormtaylor** [comment]
Late, but I also take @MoOx's approach. Having the extra branch doesn't affect anything, generally makes the entire workflow easier to reason about, and prevents the few edge-case collisions that can happen.

**Comment by mcdonnelldean** [comment]
@ianstormtaylor I think we are going to actually put the site on Surge.io in the end. While gh_pages is great what we are finding is it makes the site less manageable and prone to someone doing something wrong. All the contributors have access to push their anyway so it's all good :D 

We are even writing a few plugins :+1:
