### ISSUE TITLE
Configuration in package.json

### ISSUE THREAD

**Issue by paulcpederson** [segmentio/metalsmith#141]
I've been using a few tools like Browserify that allow you to configure them by adding a key to `package.json`. Did anybody consider something like that for Metalsmith? The content of `metalsmith.json` would just be in `package.json`:

```json
{
 ...,
  "scripts": {
    "build": "metalsmith"
  },
  "metalsmith": {
    "source": "src",
    "destination": "build",
    "plugins": {
      "metalsmith-drafts": true,
      "metalsmith-markdown": true,
      "metalsmith-permalinks": "posts/:title",
      "metalsmith-templates": "handlebars"
    }
  },
  "dependencies": {
    "metalsmith": "^1.7.0"
  },
  ...
}
```

Maybe that is a terrible idea, but wanted to ask if anybody had considered. Would be glad to attempt to pr that behavior.

**Comment by nikolaswise** [comment]
Right now I'm using the package.json **as** the config file, which lets be put the metalsmigh config keys in there.

```
  "scripts": {
    "start": "npm run dev",
    "dev": "npm run html && parallelshell 'cd build/ && live-server --port=8080' 'rerun-script'",
    "html": "metalsmith -c package.json"
  },
  "metadata": {
    "title": "nikolas wise",
    "description": "Printmaker, artist, graphic designer, and front end developer. Design focuses on the use of classical typographic and design principles with contemporary technology. Artistic practice concerns geographic specificity and knowledge of place."
  },
  "plugins": {
    "metalsmith-markdown": {},
    "metalsmith-permalinks": {},
    "metalsmith-templates": {
      "engine": "handlebars"
    }
  }
```

It would be ideal to have these keys live under

**Comment by ianstormtaylor** [comment]
I think it makes more sense for Browserify which is working with the `package.json` contents for it's other operations, since it's very tightly coupled to the package manager. But not really sure it makes sense to combine these things in Metalsmith's case, which is detached from everything in `package.json`.

Feel free to discuss more though!
