### ISSUE TITLE
Should every plugin be responsible for removing source files?

### ISSUE THREAD

**Issue by christophercliff** [segmentio/metalsmith#145]
Plugins are generally responsible for taking a source file and transforming it into something else, e.g. LESS to CSS. I get a lot of open issues like, "Why doesn't the plugin remove the `.less` files?". Would like to open it up for discussion.

If the plugin is responsible for removing source files, each one will implement some variation of `shouldKeepSourceFiles` and users will need to deal with the inconsistencies. I think a better approach is to use https://github.com/segmentio/metalsmith-ignore. That way, plugin authors avoid implementing redundant cleanup code and users get a consistent interface.

Related issues:

- https://github.com/christophercliff/metalsmith-less/issues/17
- https://github.com/christophercliff/metalsmith-fingerprint/issues/5

**Comment by ianstormtaylor** [comment]
Interesting! With the updated `recursive-readdir` and the `#ignore(files)` method, this should actually be possible in core now. Good call on that being a simple solution.

Side note, I kind of would have assumed that the plugins would transform and remove old ones. But could see why it might be something edge cases wouldn't want.

**Comment by cameronjroe** [comment]
I'm currently using metalsmith-ignore to handle this but it feels very hacky. I agree with @ianstormtaylor that it should be handled in the plugins. If plugin developers use `metalsmith.ignore()`, they'll be able to specify which files should be ignored from that plugin.

**Comment by Ajedi32** [comment]
I'm not actually sure what `ignore` has to do with anything here. As I understand it, `ignore` is only used when reading files from the directory, before any plugins are even run, so you can't use it _in_ a plugin to ignore files.

**Comment by cameronjroe** [comment]
@Ajedi32 How does one remove files from a metalsmith plugin?

**Comment by Ajedi32** [comment]
Just remove it from the files object: `delete files[filename]`

**Comment by cameronjroe** [comment]
Okay yeah that's what I've been doing. You can also use ignore. Maybe not `metalsmith.ingore()` but  them `metalsmith-ignore` package from within your build.
