### ISSUE TITLE
Incorrect build output

### ISSUE THREAD

**Issue by nikmartin** [segmentio/metalsmith#149]
Since metalsmith is a 'collection of plugins', I have no idea where to start to try to get this resolved, so I took the trickle down approach. :smile: 

I have a basic set of plugins chained together like this. I have replaced the source with an actual repo that exhibits this: 

https://github.com/nikmartin/metalsmith-builderrors

No errors are ever output, so I really have no idea where to try to run down why the partials get output more than once, but only part of the time. This makes me feel like this is some type of asynchronous race condition.

**Comment by nikmartin** [comment]
This appears to be caused by the collections plugin. It isn't documented very well, and it's behavior with multiple collections is undefined, and doesn't work. for example"

```
.use(collections({
  blog: {
    pattern: 'content/blog/*.md',
    sortBy: 'date',
    reverse: true
  },
  releases: {
    pattern: 'content/releases/*.md',
    sortBy: 'date',
    reverse: true
  }
}))
```

Doesn't work, but if I do:

```
  .use(collections({
        releases: {
          pattern: 'content/releases/*.md',
          sortBy: 'date',
          reverse: true
        }
      }))
      /*
      ,
      blog: {
        pattern: 'content/blog/*.md',
        sortBy: 'date',
        reverse: true
      }
      */
```

The collectiuons plugin (or SOMETHING) continues to process the blog as a collection, even though it is commented out

**Comment by nikmartin** [comment]
Here's a complete test case that wwill not output properly: https://github.com/nikmartin/metalsmith-builderrors
if you fecth and build that,  go to the releases, then click a link to an individual release, and you'll see what I mean

**Comment by nikmartin** [comment]
I have isolated the issue to here:
https://github.com/nikmartin/metalsmith-builderrors/blob/master/templates/partials/footer.hbs#L105

If I remove that block, everything compiles fine. I'm investigating the helper that we wrote, but don't really see why it corrupts the output buffer

**Comment by ianstormtaylor** [comment]
Hey @nikmartin thanks for the report. Not sure what you've discovered since, but can you re-open https://github.com/segmentio/metalsmith-collections if it's still an issue. Just want to clean out the core issues.
