### ISSUE TITLE
Version 2.0.1 broken?

### ISSUE THREAD

**Issue by woodyrew** [segmentio/metalsmith#151]
The following code copies files from `src` to `build` on 1.7.0
```javascript
var Metalsmith = require('metalsmith');

Metalsmith(__dirname)
    .destination('./build')
    .build(function (err) {
        // For error handling
        if (err) {
            throw err;
        }
    });
```

However, 2.0.1 errors with:
```bash
/home/my_path/node_modules/metalsmith/lib/index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/woody/Documents/test/node_modules/metalsmith/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Is this a problem or do I need to change how I'm using Metalsmith.

Node: v0.10.29

**Comment by kvzivn** [comment]
I have the same issue:

```
/Users/keiv/dev/github/blog/node_modules/metalsmith/lib/index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/keiv/dev/github/blog/node_modules/metalsmith/index.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Running Node v0.12.7

**Comment by kvzivn** [comment]
Solved. You need to run it with `node --harmony index` since the asterix (*) is part of ES6.

**Comment by woodyrew** [comment]
Odd - Metalsmith 1.7.0 uses the same syntax.  See line 190 from `/lib/index.js`
```js
Metalsmith.prototype.build = unyield(function*(){
```

See: [Metalsmith_1.7.0/index.js:190](https://github.com/segmentio/metalsmith/blob/d005f023a0df7e272752ace6eed7b9a049f5b078/lib/index.js#L190)

**Comment by MoOx** [comment]
2.0 means breaking change https://github.com/segmentio/metalsmith/blob/master/History.md#200--2015-07-14

**Comment by woodyrew** [comment]
I missed the v0.10 support stopping.  Doesn't explain why @kvzivn was getting the same issue in v0.12.

**Comment by MoOx** [comment]
This rely on generator, so `node --harmony` might help.
Note that you can use it with babel-node or via gnode.

**Comment by eddywashere** [comment]
Metalsmith 2.0.1 does not "just" work for me on node v0.12.7. I can understand dropping support for node v0.10 but not supporting v0.12 out of the box will be a rough experience for people.

To fix the error `SyntaxError: Unexpected token *`  you'll need to install harmonize and require it within your build file. Here is a quick fix:

```sh
npm install harmonize --save-dev
```

and at the top of your build file add:

```node
require('harmonize')();
```

If you're using a `metalsmith.json`, using `node --harmony` might work. I haven't tested.

There should be something in the README to talk about this. Also, maybe this is something metalsmith should add over here https://github.com/segmentio/metalsmith/blob/eb43dfdb3fc7ccd5f9c7b1b501819c07cea8d162/lib/index.js#L1

**Comment by battlemidget** [comment]
@eddywashere how did you install node 0.12.7?

**Comment by eddywashere** [comment]
@battlemidget I used brew originally to install v0.10.0, then n to install v0.12.7. But I also just tried upgrading the local brew installed version of node to 0.12.7. 

Looks like I can just add `--harmony` to the task I was running with gulp. I'll update my previous comment.

**Comment by kvzivn** [comment]
@battlemidget it's the current version. https://nodejs.org/

**Comment by davidknezic** [comment]
Will have to downgrade to `1.7.0` until this gets resolved. I also run on a standard, brewed Node `0.12.7`. Adding `--harmony` just because one tiny module requires it is no option.

**Comment by MoOx** [comment]
It's not "a tiny module". Lot's of things in core use generators.

**Comment by reedspool** [comment]
As a new user, this thread is confusing to me but I'm experiencing this problem. Installing and requiring harmonize does not fix the problem, nor does --harmony. Is there an easy path to downgrading, say by filling in my package.json correctly?

Here's my current set up, after following the harmonize instructions:

<img width="424" alt="screen shot 2015-08-20 at 2 12 25 pm" src="https://cloud.githubusercontent.com/assets/602877/9391585/8a475f1a-4745-11e5-9035-17737d23a8e9.png">

**Comment by ahmadnassri** [comment]
for those watching this thread, I added some thoughts about this [here](https://github.com/segmentio/metalsmith/issues/161#issuecomment-135077152)

**Comment by jamshark70** [comment]
I just encountered this issue. Tried the workaround with `npm install --save-dev harmonize` and npm fails to locate the package:

```
$ npm intall harmonize --save-dev

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, upgrade,
    v, verison, version, view, whoami
```

???

**Comment by somudcis** [comment]
I'm also having the same issue as @woodyrew  has.
Node version: v0.12.2.
npm version: 2.7.4

I tried the above options by installing harmonize and other few options. Still no gain.

**Comment by Ajedi32** [comment]
@somudcis If you're having trouble figuring out how to use the `--harmony_generators` flag, the easy solution is to switch to io.js or wait for the [nodejs 4.0 release](https://github.com/nodejs/node/issues/2522#issuecomment-137447506). Both of those support generators by default, so they should work with metalsmith without any flags.

**Comment by woodyrew** [comment]
@somudcis I have written a troubleshooting guide for this issue to go in the main readme, you can find it here until it's merged: https://github.com/woodyrew/metalsmith/commit/d47fed51268933d543d4953372331fa07ef0fbdb?short_path=1e290ac#diff-1e290ac8433d555bce009b162cb869d0

If any of the information is incorrect or could be better phrased please let me know on the PR #163

**Comment by woodyrew** [comment]
Explained with: https://github.com/segmentio/metalsmith#troubleshooting

**Comment by somudcis** [comment]
@woodyrew Thanks a lot. It works for me now

**Comment by jmatsushita** [comment]
As mentioned above installing io.js also solves the problem and should probably be mentioned in the troubleshooting section too.

**Comment by Ajedi32** [comment]
@jmatsushita Yeah, io.js is basically just node versions 1-3, so it also solves the problem. Only Node 0.12.x and below has this issue.
