### ISSUE TITLE
Error: "engine" option required (metalsmith-templates/lib/index.js:37)

### ISSUE THREAD

**Issue by jamshark70** [segmentio/metalsmith#164]
```
$ node index
/home/dlm/Documents/web/tests/metalsmith/node_modules/metalsmith-templates/lib/index.js:37
  if (!opts.engine) throw new Error('"engine" option required');
                          ^
Error: "engine" option required
    at plugin (/home/dlm/Documents/web/tests/metalsmith/node_modules/metalsmith-templates/lib/index.js:37:27)
    at Object.<anonymous> (/home/dlm/Documents/web/tests/metalsmith/index.js:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I am not a web design expert -- metalsmith was recommended to me as a static-site generator. Following instructions at http://www.robinthrift.com/posts/metalsmith-part-1-setting-up-the-forge/, the above is what I get. I don't know what to do next. Thanks.

**Comment by jamshark70** [comment]
My index.js:

```
var harmony    = require('harmonize')(),
    Metalsmith = require('metalsmith'),
    markdown   = require('metalsmith-markdown'),
    templates  = require('metalsmith-templates');


Metalsmith(__dirname)
    .use(markdown())
    .use(templates())
    .use(templates('handlebars'))
    .destination('./build')
    .build(function (err) { if(err) console.log(err) })
```

node version: 0.12.7

**Comment by woodyrew** [comment]
You've got two instances of `use(templates(...`

Get rid of the first so it you have something like:
```js
require('harmonize')();
var Metalsmith = require('metalsmith');
var markdown   = require('metalsmith-markdown');
var templates  = require('metalsmith-templates');

Metalsmith(__dirname)
    .use(markdown())
    .use(templates('handlebars'))
    .destination('./build')
    .build(function (err) { if(err) console.log(err) });
```

**Comment by jamshark70** [comment]
On August 29, 2015 12:04:40 PM Woody <notifications@github.com> wrote:

> You've got two instances of `use(templates(...`
>
> Get rid of the first so it you have something like:

Oh. That's embarrassing. I'm not at my computer now but I'll try it later. 
Thanks.

(It looked like a compilation error -- I had hit a different compile error 
before, hence the require('harmonize') -- and I thought this might be a 
similar issue. If it's in fact a usage error, then I apologize for misusing 
the bug tracker.)

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by jamshark70** [comment]
Ah, right, that was it. And now I see that calling `templates` without an argument would quite naturally produce the error that the engine was not specified. Now I just have to figure out why I wrote `use(templates())` in the first place *hangs head in shame* ;)

Thanks for the help. Closing.
