### ISSUE TITLE
Files appearing in strange places

### ISSUE THREAD

**Issue by donovanh** [segmentio/metalsmith#176]
I'm using Metalsmith to generate a static site. I may be doing something odd but I'm seeing each of the files I'm creating resulting in not only a folder with index file in the build folder, but all the javascript/scss folders being copied in too:

<img width="148" alt="screen shot 2015-09-29 at 22 25 22" src="https://cloud.githubusercontent.com/assets/853536/10178708/4fd38c7c-66f9-11e5-948c-583d79e9c1c9.png">

(In this image, the "about.md" file has been processed and results in not only the "about" folder with corresponding index file, but the assets folders also.

My repo is here. Would appreciate any tips if I've messed it up somehow!

https://github.com/donovanh/metalsmith-static-site

**Comment by woodyrew** [comment]
All files by default are copied from `content` (source) to `build` (destination). That accounts for the javascript and scss folders. You're better off putting your static assets outside of your `content` directory.

The [permalinks plugin](https://github.com/segmentio/metalsmith-permalinks) will change `about.md` to `about/index.html`

The [Metalsmith Slack Community] is a good place to ask questions.

**Comment by Ajedi32** [comment]
Seems like this is the result of the `metalsmith-permalinks` plugin. That's my guess anyway. I think it's copying the folders so that relative links to assets in your pages don't break.

**Comment by donovanh** [comment]
Good call on the permalink plugin. I thought I'd commented each plugin out and tested it but must have missed that. Thanks for the replies.

**Comment by woodyrew** [comment]
@donovanh: Is this still an issue? If not, it'd be good to close it.

**Comment by donovanh** [comment]
Yep it was the permalink plugin - I've stopped using it as it doesn't seem to work as I'd hoped. Closing this as it's not an issue.
