### ISSUE TITLE
Issue joining Slack channel

### ISSUE THREAD

**Issue by ijy** [segmentio/metalsmith#184]
I've tried for the past couple of days but am unable to join the new Slack channel. Following the link on the metalsmith homepage leads to:

<img width="794" alt="screen shot 2015-10-31 at 09 34 42" src="https://cloud.githubusercontent.com/assets/434593/10862880/e3155502-7fb2-11e5-907f-2a7f6a2f7d24.png">

Previously I could see the screen but upon entering my email and clicking on `request an invite` it would return "token_revoked".

**Comment by woodyrew** [comment]
Hi @ijy, are you still having this issue?  I had a _blip_ with connectivity but it seems fine now. Is this still an issue for you?

**Comment by ijy** [comment]
Still getting the same thing unfortunately. It's been at least a day long blip for me. :)

**Comment by woodyrew** [comment]
Try: https://metalsmith.slack.com

**Comment by ijy** [comment]
Well, that works but I don't have an @segment.com email address to join with...?

**Comment by woodyrew** [comment]
I see what you're talking about: ![2015-10-31_10e4](https://cloud.githubusercontent.com/assets/1902064/10866217/b49badca-800c-11e5-861f-e66f66a79d0e.png)

I've posted in the help section on the Slack channel, hopefully someone will help you out soon.

**Comment by lambtron** [comment]
http://metalsmith-slack.herokuapp.com/

I had to upgrade to v0.6.0 of [Slackin](https://github.com/rauchg/slackin) and it works now. The issue is referenced [here](https://github.com/rauchg/slackin/issues/112).

**Comment by ijy** [comment]
Now it tells me that I need to be part of a paid team:

<img width="315" alt="screen shot 2015-11-01 at 09 36 35" src="https://cloud.githubusercontent.com/assets/434593/10868141/255b5f82-807c-11e5-9ea3-c7fc6b6d6f81.png">

Would it not be easier to go with IRC?

**Comment by Ajedi32** [comment]
IRC isn't nearly as accessible as Slack IMO. A lot of users don't already have an IRC client, so they'd need to set one up in order to join the channel. Compared to the very familiar process of signing up for another online service, IRC generates a lot of extra friction.

**Comment by woodyrew** [comment]
I agree that's the perception but it doesn't have to be reality:<iframe src="http://webchat.freenode.net?channels=%23metalsmith&uio=d4" width="647" height="400"></iframe>

**Comment by Ajedi32** [comment]
@woodyrew Yeah, that's kinda what I meant. IRC is just a protocol, so you can of course theoretically implement any front end on top of it that you want, including a Slack-like web UI.

In practice though Slack seems to be quite a bit nicer. They spent a lot more time polishing the user experience than most IRC clients I'm aware of.

**Comment by ijy** [comment]
I don't really mind what is used as long as it works. At the moment the above problem still remains. The issue has been closed prematurely. Can it please be re-opened and looked at?

**Comment by lambtron** [comment]
Sorry, I accidentally included an option in there that allowed Single slack channel invite which is a feature reserved for paid teams.

https://github.com/rauchg/slackin/issues/79

I removed that option and now it should work. Please let me know if problems persist.
