### ISSUE TITLE
Use lab and Code for testing

### ISSUE THREAD

**Issue by AdrieanKhisbe** [segmentio/metalsmith#215]
I'm proposing to migrate our testing to use `lab`test runner and `code` asserter.

[Lab](http://github.com/hapijs/lab) come with builtin coverage, beside on failing test doesnt terminate the testing. (hence you could detect several failing test. -> that was a pain pouring some es6 into metalsmith).

[Code](http://github.com/hapijs/code) assertions are also more expressive, and capture more semantics.

I can take of this, should you agree :)

**Comment by Ajedi32** [comment]
> on failing test doesn't terminate the testing

FYI, that's not default behavior for Mocha either. Here's the culprit: https://github.com/metalsmith/metalsmith/blob/master/test/mocha.opts#L4

**Comment by AdrieanKhisbe** [comment]
incoming!!

**Comment by AdrieanKhisbe** [comment]
(shall I do it in the #214 PR, or a dedicated?
if we consider that #214 will be merge, that will avoid us an extra merge commit)

**Comment by Ajedi32** [comment]
Make it in a separate PR. I want to double-check that no one else has any objections to removing that option before merging it, so it'd be good to have a separate PR to point to.

**Comment by AdrieanKhisbe** [comment]
Nopro!

**Comment by Ajedi32** [comment]
Regarding this proposal, I will say I'm a bit skeptical. Mocha is a pretty popular test framework with a large ecosystem and strong community support, and I'm not quite sure I see any huge benefits to switching to Lab.

Code looks pretty nice though, and I don't think I'd personally mind using that in our existing tests.

Although... one thing I did notice that Lab might give us is support for source maps in our test coverage. (Which we will probably want for #214). Istanbul is working on support for that, but it doesn't seem fully baked yet: gotwarlost/istanbul#212

**Comment by AdrieanKhisbe** [comment]
I see your points.
The main difference between lab and mocha in term of dsl is that all it takes a function with a `done` callback.
Two benefits of lab is indeed the builtin coverage, and also the builtin linter (relint on `.??hintrc`)

I let you decide. There is no urgency, and it's just a suggetsion :)

**Comment by Ajedi32** [comment]
FYI, Mocha supports a done callback too for asynchronous tests. It also supports Promises, which is super-nice IMO. (You can return a promise from the test case, and the test will either fail or pass once the promise resolves.)

**Comment by AdrieanKhisbe** [comment]
I knew for the async callback. But didn't know about the promise. 
Thanks for this piece of information ;)
