### ISSUE TITLE
Collections: only refer with a specific metadata

### ISSUE THREAD

**Issue by mytototo** [segmentio/metalsmith#228]
Hey guys!

I started working with Metalsmith and some plugins such as `collections`, `markdown`, `layouts`, and `permalinks`. Looks really good for now.

I have several collections and each one of them has some files in it. I can paginate thanks to the `collections` plugin, works well. However I have some additional metadata in my files like `subject` which is a string. Example:

``` md

---
collection: news
title: Welcome to my blog
slug: welcome
draft: false
subject: misc

---

# Welcome

Here is some markdown.
```

How can I refer an entry to the previous and next entry with the same `subject` as the current one?

For example, if I refer to the next entry I can have an entry which has the `subject` `dev`. I only want the next entry which has the subject `misc`. How is it possible?

Thanks for your support.

**Comment by fenwick67** [comment]
You'll need to write your own plugin.

I'd advise creating a "next" and "previous" key on each post which refers to another file.  Then, when you template it, refer to those properties.  This is what I did for my blog, check out some of the [code] (https://github.com/fenwick67/fenwick67.github.io/blob/81de5ba31a51ab83a5a190a67119332a8635197b/_blog/lib/parse-meta.js#L24) and [template](https://github.com/fenwick67/fenwick67.github.io/blob/81de5ba31a51ab83a5a190a67119332a8635197b/_blog/post.jade#L21).

**Comment by jocelynlecomte** [comment]
I think @fenwick67 was right in his first comment, the one he crossed out. `next` an `previous` navigate through the collection content, whether or not the `subject` is the same.
And I don't know any plugin doing that sort of thing for now.
