### ISSUE TITLE
Date format in front-matter

### ISSUE THREAD

**Issue by alexandrubau** [segmentio/metalsmith#282]
Hi guys,

I'm having a little bit of trouble understanding why the `date` variable from front-matter gets translated into `new Date(date)`. Also if I change the format, it doesn't get translated anymore.

Where does this transformation come from? Is it from Metalsmith? 
If it is so, I think it should be specified in the docs.

Thanks.

**Comment by Ajedi32** [comment]
Front-matter in Metalsmith is written in YAML. So see the section of the YAML specification on timestamp values: http://yaml.org/type/timestamp.html

This behavior is not specific to Metalsmith. All YAML parsers which support the timestamp type will behave this way.

**Comment by alexandrubau** [comment]
Thank you very much @Ajedi32 . I did not know that.
