### ISSUE TITLE
`source` and `destination` are ignored in JavaScript configuration file

### ISSUE THREAD

**Issue by sigo** [segmentio/metalsmith#284]
I've installed `metalsmith: "2.3.0"` and I created simple JavaScript config:

```
const metalsmith = require("metalsmith");

metalsmith(__dirname)
    .source("sourcepath")
    .destination("destpath");
```

When I'm trying run metalsmith, I have return from console:

```
Metalsmith · ENOENT: no such file or directory, scandir '/Users/sigo/Sources/sigosite/src'

Error: ENOENT: no such file or directory, scandir '/Users/sigo/Sources/sigosite/src'
```

I think that both `source` and `destination` are ignored in JavaScript configuration file. Json-way is working correctly.

To be sure, I've copied few examples from official website, and it's all (not)working the same way.

**Comment by Ajedi32** [comment]
That's pretty weird, since the JSON config uses exactly the same API you're using here. Not to mention that you didn't call `build()` in the above sample code, which should mean that Metalsmith never gets executed at all.

**Comment by sigo** [comment]
@Ajedi32 ouch...

I'm using `metalsmith` command (CLI) with JavaScript file. I thought it's totally correct. **Using `node <config-file>js` works perfect.**

At this moment, this isn't bug - this is my mistake. Thanks!

---

One weird thing: when you define config:

```
const metalsmith = require("metalsmith");

metalsmith(__dirname)
    .source("sourcepath")
    .destination("destpath")
    .build((err) => {
        if (err) {
            throw err;
        }
    }
);
```

and run it with `metalsmith -c <config>.js`, it works and create (sic!) two destination directories - default `build/` and defined above `destpath/` with identical content.
