### ISSUE TITLE
is it possible to specify file path rather than directory in .source('./src/index.md') ??

### ISSUE THREAD

**Issue by gkumar77** [segmentio/metalsmith#293]
According to my requirement i need to specifically give file path in .source() metalsmith.js file.

```
var Metalsmith  = require('metalsmith');
var markdown    = require('metalsmith-markdown');
var layouts     = require('metalsmith-layouts');
var permalinks  = require('metalsmith-permalinks');
var fs =require('fs');
var Handlebars = require('handlebars');

Handlebars.registerPartial('header2', fs.readFileSync(__dirname + '/layouts/partials/header2.html').toString());
Handlebars.registerPartial('footer3', fs.readFileSync(__dirname + '/layouts/partials/footer3.html').toString());
Handlebars.registerPartial('header1', fs.readFileSync(__dirname + '/layouts/partials/header.html').toString());
Handlebars.registerPartial('footer2', fs.readFileSync(__dirname + '/layouts/partials/footer2.html').toString());
Metalsmith(__dirname)
  .metadata({
    title: "My Static Site & Blog",
    description: "Hello FLowz welcome you!!!",
    generator: "Metalsmith",
    url: "http://www.metalsmith.io/"
  })
  .source('./src/index.md')
  .destination('./build')
  .clean(false)
  .use(markdown())
  .use(permalinks())
  .use(layouts({
    engine: 'handlebars'
  }))
  .build(function(err, files) {
    if (err) { throw err; }
  });
```
P.S
i know it seems a weird question but you will be helpful.Thank you

**Comment by Ajedi32** [comment]
`source` needs to be a directory, not a file.

**Comment by leviwheatcroft** [comment]
you probably want metalsmith-ignore

`.use(ignore('!index.md'))`

**Comment by gkumar77** [comment]
@leviwheatcroft ty but i guess i need the file and not ignore it.
 _Metalsmith-ignore plugin to ignore files that match a pattern._

```
.use(ignore('!contact.md'))

Error: ENOTDIR: not a directory, scandir '/home/software/workspace/metalsmith/examples/static-site/src/contact.md'
```

**Comment by leviwheatcroft** [comment]
Not sure but is that error maybe thrown because your `source` is still pointing to a file instead of a dir?

```
.source('./src')
.use(ignore('!contact.md')
```

So `source` includes the whole dir, then `ignore` ignores everything except for `contact.md` (because of the `!` negative match)

**Comment by Ajedi32** [comment]
@leviwheatcroft Yeah that should work. Though rather than `.use(ignore('!contact.md')` it might be better to use `.ignore('!contact.md')`. The later is more efficient since it ignores the files before reading them into memory, whereas the ignore plugin can only act on the files after they've already been loaded into memory by Metalsmith.

**Comment by gkumar77** [comment]
@Ajedi32 Thank you .
@leviwheatcroft yeah that seems a good idea. Thanks

**Comment by leviwheatcroft** [comment]
@Ajedi32 nice! I didn't know that was a thing.
