### ISSUE TITLE
metalsmith.io is down

### ISSUE THREAD

**Issue by kosirm** [segmentio/metalsmith#300]
Hi I just noticed that metalsmith.io is down with some heroku application error.

**Comment by jonathanlinat** [comment]
I confirm.

![image](https://user-images.githubusercontent.com/14064112/34261087-d1d65bc2-e646-11e7-8f73-b0102a10db33.png)

**Comment by evbogue** [comment]
Paging @ianstormtaylor

**Comment by ianstormtaylor** [comment]
cc @lambtron @calvinfo

**Comment by calvinfo** [comment]
Thanks for flagging! Just updated the account, it should be up now.

**Comment by kosirm** [comment]
It's up! Thanks!
