### ISSUE TITLE
latest versions yields 'Error: no files to process.' for static-site

### ISSUE THREAD

**Issue by DavidBiesack** [segmentio/metalsmith#319]
I created a new project similar to example/static-site and when running `node index.js` I got the `Error: no files to process.' error.

This occurred because my project used `npm i metalsmith metalsmith-layouts metalsmith-markdown metalsmith-permalinks`

If I set up static-site, `make` works, but if I update the versions to the most recent, I get the error
```
$ npm remove metalsmith metalsmith-layouts metalsmith-markdown metalsmith-permalinks
$ npm install metalsmith metalsmith-layouts metalsmith-markdown metalsmith-permalinks
$ make
node index.js
/private/tmp/static-site/index.js:22
    if (err) { throw err; }
               ^

Error: no files to process. See https://www.npmjs.com/package/metalsmith-layouts#no-files-to-process
    at Ware.<anonymous> (/private/tmp/static-site/node_modules/metalsmith-layouts/lib/index.js:141:7)
    at Ware.<anonymous> (/private/tmp/static-site/node_modules/wrap-fn/index.js:45:19)
    at Immediate.next (/private/tmp/static-site/node_modules/ware/lib/index.js:85:20)
    at Immediate.<anonymous> (/private/tmp/static-site/node_modules/wrap-fn/index.js:121:18)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
make: *** [build] Error 1
```

**Comment by DavidBiesack** [comment]
I read https://www.npmjs.com/package/metalsmith-layouts#no-files-to-process but I till don't know how to resolve the error. I'm using the `examples/static-site` on this project, but with latest dependencies, it fails. It should have something to do - there are several *.md files
to process.

I tried to explicitly add
```
  npm install jstransformer-handlebars
  npm install jstransformer-markdown
```
but `make` in your static-site still fails with the latest metalsmith-*
Only reverting versions back to https://github.com/segmentio/metalsmith/blob/master/examples/static-site/package.json works.

Please update [`examples/static-site`](https://github.com/segmentio/metalsmith/tree/master/examples/static-site) so that it works with the latest version of the metalsmith-* dependencies. Thanks.

**Comment by ismay** [comment]
Yeah those examples are two years old, and you’re using the latest version of layouts, which is much newer. So that’s why it doesn’t work. There have been breaking changes in the meantime.

For up to date examples take a look at https://github.com/metalsmith/metalsmith-in-place/wiki We’re still in the process of doing the same for layouts.

> Please update examples/static-site so that it works with the latest version of the metalsmith-* dependencies. Thanks.

Help is always welcome david.

**Comment by DavidBiesack** [comment]
See PR #320 to update examples/static-site to use metalsmith-in-place and Markdown transformer
