### ISSUE TITLE
[question] what does done do for plugin function

### ISSUE THREAD

**Issue by jsomedon** [segmentio/metalsmith#328]
So if I have a plugin function with all three args `files`, `metalsmith`, `done` and never make use of `done` arg, then chain that plugin function, my build doesn't fail but my destination has nothing built.

But if I have like `setImmediate(done)`, or if I remove `done` from arity, it builds fine.

I can't find any documentation on `done`, and just by looking at source code, it looks like it's related with `ware`.

**Comment by ismay** [comment]
Hi @jsomedon, it's nice that you're exploring the metalsmith ecosystem, but the issues aren't meant for questions or support requests. I closed a similar issue you opened yesterday.

As I said then, these questions are much better asked in our slack channel (http://metalsmith-slack.herokuapp.com). That's where the devs hang out and where you'll get a quick answer to questions like these. The issue tracker is **only** for tracking work that needs to be done on our software (so bugs, features, etc.).
