### ISSUE TITLE
Proposal: Development mode

### ISSUE THREAD

**Issue by HKalbasi** [segmentio/metalsmith#337]
Build process becomes more complicated over time and therefore slower. With such slow build process, development is a pain.

My solution is:
* User use `.dev()` instead of `.build()` for entering development mode.
* Metalsmith run a classical build, but plugins can find that this is initialization of a development build and disable slow optimization features. Metalsmith keep a deep copy of every step somewhere.
* Metalsmith watch the files.
* When a file changes, Metalsmith notify the first plugin that these files are changed. then plugin decide to change some file based on this changes, and return the list of changes to Metalsmith. Metalsmith notify second plugin with this new list, and so on. At the same time, Metalsmith updates its deep copies. For backward compatibility, every plugin that does not handle updates in dev mode, Metalsmith send files from deep copy classically.
* Finally, Metalsmith could notify a development server for sending reload signal to clients or something like this.

**Comment by ismay** [comment]
Thanks for the suggestion. But this usecase is already addressed with metalsmith-if and env variables:

```js
const metalsmith = require('metalsmith');
const when = require('metalsmith-if');
const inPlace = require('metalsmith-in-place');
const robots = require('metalsmith-robots');
const sitemap = require('metalsmith-sitemap');

const isProduction = process.env.NODE_ENV === 'production';

metalsmith(__dirname)
  .clean(isProduction)
  .use(inPlace())
  .use(
    when(
      isProduction,
      robots({
        sitemap: urlJoin(hostname, 'sitemap.xml'),
      })
    )
  )
  .use(
    when(
      isProduction,
      sitemap({
        hostname,
        omitIndex: true,
        omitExtension: true,
        lastmod: new Date(),
      })
    )
  )
  .build((err) => {
    if (err) {
      throw err;
    }
  });
```

You can set the env var in an npm script for example:

```
"build": "NODE_ENV=production node metalsmith.js"
```

That way, metalsmith and plugins can be agnostic to what build type you're running. I'll close this issue since I think the usecase has been addressed. But feel free to comment if you feel otherwise.

**Comment by HKalbasi** [comment]
This cover some cases but the bottleneck is building everything from first. For example I have thousands of markdown files, and I change one of them, then watcher calls metalsmith and it rebuild all those htmls just for one of them.

**Comment by ismay** [comment]
I see. In that case, I think that something like https://www.npmjs.com/package/metalsmith-changed is what you want.
