### ISSUE TITLE
generic pipeline branching/ source file filtering

### ISSUE THREAD

**Issue by ericgj** [segmentio/metalsmith#40]
Plugins basically do their own filtering of source files, sometimes it's hard-coded and sometimes in options, etc. 

I was feeling the need for a more declarative way to say "run this list of middleware on these selected files", so I put together [metalsmith-branch][branch]. It's not entirely tested yet but see what you think.

```js
metalsmith.use( 
  branch('*.md')        // for only md source files,
    .use( templates({       // run through swig template engine
               engine: "swig",
               inPlace: true
          })
    )
    .use( markdown() )      // and generate html
)
.use(  /* plugin to be run on all files */ )
```
[branch]: https://github.com/ericgj/metalsmith-branch

**Comment by ianstormtaylor** [comment]
Closing because I think it makes sense to keep it as a plugin, instead of adding complexity to core.
