### ISSUE TITLE
Directories with titles of other posts appearing inside some post directories

### ISSUE THREAD

**Issue by Sneagan** [segmentio/metalsmith#54]
I'm still trying to track down where this is coming from, but when I build I'm getting a directory structure that looks like this:

    |-posts
        |-post1
            |-index.html
        |-post2
            |-index.html
            |-post1 [empty directory]

This is very consistently happening. Still hunting.

**Comment by ianstormtaylor** [comment]
Closing this since it's old, but feel free to re-open!
