### ISSUE TITLE
Categories or Tags?

### ISSUE THREAD

**Issue by jmatsushita** [segmentio/metalsmith#59]
Hi there,

Really like the design of Metalsmith but got blocked when trying to reproduce a Tag or Category functionality with the existing plugins. More specifically I'm talking about accessing all posts in a category or tag with a tag.\* approach and being able to add tag (and multiple tags) metadata. Cherry on top would be hierarchical Categories like in Hexo.

Am I missing something obvious or should I wait for @lasar with https://github.com/lasar/metalsmith-tags?

Cheers,

Jun

**Comment by ainthek** [comment]
http://www.gelatindesign.co.uk/blog/post/creating-a-blog-with-metalsmith/ broken link ?

**Comment by Ajedi32** [comment]
@ainthek https://web.archive.org/web/20141229232114/http://www.gelatindesign.co.uk/blog/post/creating-a-blog-with-metalsmith

**Comment by budparr** [comment]
http://www.gelatindesign.co.uk/coding/creating-a-blog-with-metalsmith/
