### ISSUE TITLE
Documentation site example

### ISSUE THREAD

**Issue by rahul286** [segmentio/metalsmith#62]
I am trying to create a documentatio site like - https://segment.io/docs/

Can anybody please point me to valid example/sample sites which has above site like structure? i.e. pages, sub-pages, navigation, etc.

**Comment by ianstormtaylor** [comment]
We're going to be publishing a blog post on how we built the Segment docs with Metalsmith soon hopefully, but closing for now since this ticket is old and not really solveable by core :)
