### ISSUE TITLE
Throw EMFILE errors

### ISSUE THREAD

**Issue by bradparker** [segmentio/metalsmith#65]
Hi all, 

Thanks so much for the awesome project. Sooo flexible, sooo easy to get up and running.

When reading in large projects (~10mb+) it seems that blowing out the `ulimit` causes metalsmith to fail silently. While I know I really should be splitting up such an big project, it took a while to track down the cause of the issue.

Let me know if I can provide any more info.

Cheers,
Brad

**Comment by ianstormtaylor** [comment]
Would accept a PR for this that limits the concurrency!

**Comment by tschaub** [comment]
> Would accept a PR for this that limits the concurrency!

See #130.
