### ISSUE TITLE
Multi Language Support?

### ISSUE THREAD

**Issue by GutenYe** [segmentio/metalsmith#70]
Is there already a solution out there? Or if not, any plan to support it?

For template, implement a `I18n.t(key)` function is easy, but data from json or markdown file need a way to stored and used. I think it need to be built into the core, so that plugins can follow the convention and support it.

**Comment by doup** [comment]
@GutenYe did you solve this somehow? I'm going to start with a localized website and wanted to know how did you set your project.

**Comment by ianstormtaylor** [comment]
Closing but feel free to re-open with a suggestion, or description of the core issue, or a pull request with required functionality for multi-language support.

**Comment by doup** [comment]
Finally I've migrated to Metalsmith the website I had in mind when I was asking about this issue… and since it was multi-language I've extracted the plugins for your pleasure. ;-)

https://github.com/doup/metalsmith-i18n
https://github.com/doup/metalsmith-multi-language

Ping @gutenye @RobLoach

**Comment by gutenye** [comment]
@doup That're great plugins and will certainly fit my needs, thank you :+1:

**Comment by RobLoach** [comment]
@doup Well done! Great to see this come into place. Where have you been using it?

**Comment by doup** [comment]
@RobLoach check this: http://www.grupreflexioautonomia.org and here the code: https://github.com/grautonomia/web

**Comment by revolunet** [comment]
Thanks @doup ! :+1:
