### ISSUE TITLE
epub plugin / example

### ISSUE THREAD

**Issue by isaaki** [segmentio/metalsmith#71]
The Metalsmith website is quite explicit about the ability to use it for generating ebooks... only a plugin / example seems to be lacking. Am I missing something, or should it be simple enough to piece together such a setup without the need for a plugin?

**Comment by ianstormtaylor** [comment]
Ah nope, it's *possible* to make it generate ebooks, but it's just an example of what can be done. No plugins exist to make it happen yet, but anyone could write one!
