### ISSUE TITLE
included (external) SCSS notifying watch but not building

### ISSUE THREAD

**Issue by mansona** [segmentio/metalsmith#81]
I am recording 2 bugs that are separate but share the same example code repo: https://github.com/Blooie/metalsmith-bug/tree/master

This bug is Bug 1, which is listed in the readme file but coppied here for reference: 

How to recreate:
* run ``` npm start ``` which starts metalsmith watching
* update scss/_include.scss
* notice that the console output sees that ```../scss/_include.scss was changed```
* notice that it doesn't show a ```...rebuild```

How to get it to rebuild (workaround):
* run ```npm start``` like above
* update scss/include.scss
* update contents/styles/app.scss
* notice that it now sees that ```app.scss``` has changed **and** does a ```...rebuild```

This is just a toy example, we're making use of it in a different way but if this issue was solved it would fix everything in our case.

**Comment by ianstormtaylor** [comment]
Closing since this is related to `metalsmith-watch` instead of core, which I'm not really sure I would recommend using at all, but feel free to reopen in the repository for it!
