### ISSUE TITLE
updating template file rebuilds but does not update index.html in dist

### ISSUE THREAD

**Issue by mansona** [segmentio/metalsmith#82]
I am recording 2 bugs that are separate but share the same example code repo: https://github.com/Blooie/metalsmith-bug/tree/master

This bug is Bug 2, which is listed in the readme file but coppied here for reference: 
How to recreate:
* run ```npm start``` as above
* update templates/index.hbs
* notice that it sees ```../templates/index.hbs was changed``` **and** does a ```...rebuild```
* notice that your changes are not reflected in dist/index.html

It seems like the templates engine is holding the template file in memory and just reusing it instead of reading it off disk again. Is this expected behaviour?

**Comment by ianstormtaylor** [comment]
Closing because this seems related to `metalsmith-templates` instead of core, but feel free to re-open over there, or submit a pull request.
