### ISSUE TITLE
no files showing up in build

### ISSUE THREAD

**Issue by zt9** [segmentio/metalsmith#92]
I got tired of assemble.io, and am trying out metalsmith. I am running a super simple example, but I do not see to get any output.. Running node v0.10.32 and metalsmith 1.0.1

Here is what I am doing

<code>
$ npm install metalsmith
 
 
index.js:
 
var Metalsmith = require('metalsmith');
Metalsmith(__dirname)
    .destination('output')
    .build();
    
first.md
---
title: Home
---
Hi, this is my start page; neat ain't it? ;)
 
###Some info!
 
 
My directory tree
=================
 
.
├── build
├── index.js
└── src
    └── first.md
    
Run the code
============
 
node index.js
 
I see nothing in build/

Update: I pulled 0.11 version and it works fine without any problems which indicates to me that I am not doing anything wrong. Is just does not work with the latest version..

**Comment by hunterloftis** [comment]
Sad to see this is still open :cry: anybody know the status?

Metalsmith was working great for me, just started a new project with latest and `.build()` is doing nothing. Do I need to run this in harmony mode? Pass it a generator? I think one solid, working, minimal example of using the latest version programmatically would go a long way (as the current examples definitely don't work with 1.0.1).

**Comment by comfycode** [comment]
@hunterloftis, just pass a function to the `.build()` method. 
For example:
```javascript
.build(function (err) {
    err && console.log(err);
});
```

**Comment by ianstormtaylor** [comment]
Hey all, really sorry for the delay here. I keep meaning to power on this one night after work but get distracted. Hopefully have time for it this weekend.

**Comment by ben-eb** [comment]
What needs to be done to get this resolved?

**Comment by hunterloftis** [comment]
It works fine, just needs either 1) docs that reflect the need for a callback function or 2) a fix so `build()` doesn't require a callback. Preferably 2. No worries @ianstormtaylor we appreciate the free software ;)

**Comment by unstoppablecarl** [comment]
@ben-eb I think a coordinated kidnapping of @ianstormtaylor is the next logical step.

**Comment by ben-eb** [comment]
@unstoppablecarl :+1:
