### ISSUE TITLE
Metalsmith.create() alias for constructor

### ISSUE THREAD

**Issue by christophercliff** [segmentio/metalsmith#93]
My JSHint config complains when I invoke `Metalsmith()` without the `new` keyword, however the API is suited for chainability so I end up writing code like:

```js
(new Metalsmith(__dirname))
  .use()
  // etc.
```

It would be nicer to write:

```js
Metalsmith.create(__dirname)
  .use()
  // etc.
```

I might be the only one writing JS like this ¬_¬

**Comment by ianstormtaylor** [comment]
Closing based on logic here: https://github.com/segmentio/metalsmith/pull/111
