### ISSUE TITLE
Metadata parsing fails for Markdown document

### ISSUE THREAD

**Issue by floledermann** [segmentio/metalsmith#96]
For the following, entirely well-formed Markdown document, metalsmith throws an error during metadata parsing. Note that the document does not contain any metadata, but it is currently not possible to exclude specific documents from metadata parsing.

```markdown
Who
---

`foo`

What
----
```

**Comment by ianstormtaylor** [comment]
Seems like a bug that should be solved upstream in the frontmatter parsing dependency.

**Comment by ianstormtaylor** [comment]
Fixed in `1.4.x`!
