### ISSUE TITLE
Choose metalsmith collection from .md file

### ISSUE THREAD

**Issue by fracu** [segmentio/metalsmith#99]
I've been using Metalsmith static site generator for some time and I believe is a great tool. Now I started using metalsmith-collections plugin but I stumbled across this issue.

Given the case that I have two collections defined, for instance "en_news" and "sp_news" and the following news.hbt file:

```javascript
<h1>{{title}}</h1>
{{contents}}

<ul>
    {{#each collections.en_news}}
        <li>
            <h3>{{this.title}}</h3>
            <article>{{this.contents}}</article>
        </li>
    {{/each}}
</ul>
```
Now in the .md file I want the collection to be either collection.en_news:
```javascript
---
title: News
template: news.hbt
lang-collection: en_news
---
News in english language
```
...or collection.sp_news:
```javascript
---
title: Noticias
template: news.hbt
lang-collection: sp_news
---
News in spanish language
```
How can I use "lang-collection" inside test.hbt to define the used collection?

Of course the following does not work:
```javascript
{{#each collections.{{lang-collection}}}}
```
Thanks in advance!

**Comment by sperand-io** [comment]
The collections plugin looks specifically for the `collection` property, and won't match for `lang-collection`.

So if you change that just to `collection` in the article yaml,  you should then be able to get this working via:

```
metalsmith.use(collections({
  sp_news: {
    sortBy: 'date',
    reverse: true
  }, 
 en_news: {
    sortBy: 'date',
    reverse: true
  }, 
}));
```

and in your templates: 

```
<ul>
    {{#each en_news}}
        <li>
            <h3>{{this.title}}</h3>
            <article>{{this.contents}}</article>
        </li>
    {{/each}}
</ul>
```

**Comment by fracu** [comment]
Yes, but in this case collection will be always "en_news" and never "sp_news". I would like to be able to choose between collections "en_news" and "sp_news" from the .md file.

What I want is to have only one template and use it from several languages, so I need to choose the collection from the .md files (collection shoud not be specified in the template file).

Thank you anyway.

**Comment by sperand-io** [comment]
Sorry. Should have been more clear. The property name "collection" is mandatory but you can pass it any value to designate *which* collection the file belongs in.  so if you have some files marked

```
collection:  en_news
```

and others with

```
collection:  sp_news
```

... then your index could look like

```
<ul>
    {{#each en_news}}
        <li>
            <h3>{{this.title}}</h3>
            <article>{{this.contents}}</article>
        </li>
    {{/each}}
</ul>

<ul>
    {{#each sp_news}}
        <li>
            <h3>{{this.title}}</h3>
            <article>{{this.contents}}</article>
        </li>
    {{/each}}
</ul>
```

... and both would work! :)

I *think* that's what you're looking for?

**Comment by fracu** [comment]
I didn't want to be disrespectful. I really appreciate you are taking the time to answer me. I didn't read your answer carefully enough to understand what you were trying to tell me. Sorry about that.

I added "collection" property to my yaml files after your suggestion but both collections are showing at the same time as if property had no effect. I believe I may be doing something wrong...

**Comment by sperand-io** [comment]
hey no worries! just figured i'd try to lend a hand :)

hmmm yea if you want to add me to the test case's repo I'm happy to take a look and see if we can figure it out

**Comment by fracu** [comment]
Hello Chris, I added to a repository which I just created.

In the actual web site I have two collections:
  **en_features** in **/src/en/features**
  **es_features** in **/src/es/features**

These features are used in **index.html** which is built using template **/templates/home.hbt** and markup **/src/en/index.md** and **/src/es/index.md** depending on language.

I have tried two options: 
1) Add either **collection: es_features** or **collection: en_features** to each file on **/src/es/features/** and **/src/en/features**.
2) Add either **collection: es_features** or **collection: en_features** to **/src/es/index.md** and to **/src/en/index.md**

In both cases collections are showing at the same time.

Thank you so much for your support.

**Comment by fracu** [comment]
Hello Chris, did you receive the invitation to the repo? Thank you.

**Comment by ianstormtaylor** [comment]
Closing since it's related to `metalsmith-collections` instead of core, but feel free to open an issue over there.
